#!/bin/bash
# Cloudflare Tunnel setup for J.A.R.V.I.S remote access
#
# This script helps set up a Cloudflare Tunnel to expose your local
# J.A.R.V.I.S hub to the internet securely.
#
# Prerequisites:
# - Cloudflare account (free tier works)
# - A domain managed by Cloudflare (or use *.trycloudflare.com for testing)
#
# Usage:
#   ./setup_cloudflare_tunnel.sh              # Interactive setup
#   ./setup_cloudflare_tunnel.sh --quick      # Quick tunnel (no auth)

set -e

JARVIS_PORT=${JARVIS_PORT:-18000}
TUNNEL_NAME=${TUNNEL_NAME:-jarvis-hub}

echo "=================================="
echo "J.A.R.V.I.S Cloudflare Tunnel Setup"
echo "=================================="
echo ""

# Check if cloudflared is installed
if ! command -v cloudflared &> /dev/null; then
    echo "Installing cloudflared..."

    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        if command -v brew &> /dev/null; then
            brew install cloudflared
        else
            echo "Please install Homebrew first: https://brew.sh"
            exit 1
        fi
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux
        if command -v apt-get &> /dev/null; then
            curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
            sudo dpkg -i cloudflared.deb
            rm cloudflared.deb
        elif command -v yum &> /dev/null; then
            curl -L --output cloudflared.rpm https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-x86_64.rpm
            sudo yum localinstall -y cloudflared.rpm
            rm cloudflared.rpm
        else
            echo "Please install cloudflared manually: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation"
            exit 1
        fi
    else
        echo "Unsupported OS. Please install cloudflared manually."
        exit 1
    fi
fi

echo "cloudflared version: $(cloudflared --version)"
echo ""

# Quick tunnel mode (no authentication, temporary URL)
if [[ "$1" == "--quick" || "$1" == "-q" ]]; then
    echo "Starting quick tunnel (temporary URL, no auth required)..."
    echo ""
    echo "Your J.A.R.V.I.S hub will be available at a temporary URL."
    echo "This URL changes each time you restart the tunnel."
    echo ""
    echo "Press Ctrl+C to stop the tunnel."
    echo ""

    cloudflared tunnel --url http://localhost:$JARVIS_PORT
    exit 0
fi

# Full tunnel setup with authentication
echo "Setting up persistent tunnel with Cloudflare..."
echo ""

# Check if already logged in
if ! cloudflared tunnel list &> /dev/null 2>&1; then
    echo "Logging in to Cloudflare..."
    echo "A browser window will open for authentication."
    echo ""
    cloudflared login
fi

# Check if tunnel already exists
if cloudflared tunnel list | grep -q "$TUNNEL_NAME"; then
    echo "Tunnel '$TUNNEL_NAME' already exists."
    read -p "Delete and recreate? (y/N): " recreate
    if [[ "$recreate" =~ ^[Yy]$ ]]; then
        cloudflared tunnel delete $TUNNEL_NAME
        cloudflared tunnel create $TUNNEL_NAME
    fi
else
    echo "Creating tunnel '$TUNNEL_NAME'..."
    cloudflared tunnel create $TUNNEL_NAME
fi

# Get tunnel ID
TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')
echo "Tunnel ID: $TUNNEL_ID"

# Create config file
CONFIG_DIR="$HOME/.cloudflared"
CONFIG_FILE="$CONFIG_DIR/config.yml"

echo ""
echo "Creating configuration..."

# Ask for hostname
read -p "Enter your subdomain (e.g., jarvis.yourdomain.com): " HOSTNAME

if [[ -z "$HOSTNAME" ]]; then
    echo "No hostname provided. Using tunnel URL directly."
    HOSTNAME=""
fi

mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" << EOF
# Cloudflare Tunnel configuration for J.A.R.V.I.S
# Generated by setup_cloudflare_tunnel.sh

tunnel: $TUNNEL_ID
credentials-file: $CONFIG_DIR/$TUNNEL_ID.json

ingress:
  # J.A.R.V.I.S Hub API
  - hostname: ${HOSTNAME:-"*"}
    service: http://localhost:$JARVIS_PORT
    originRequest:
      noTLSVerify: false
      connectTimeout: 30s

  # Catch-all (required)
  - service: http_status:404
EOF

echo "Configuration saved to: $CONFIG_FILE"
echo ""

# Set up DNS (if hostname provided)
if [[ -n "$HOSTNAME" ]]; then
    echo "Setting up DNS route..."
    cloudflared tunnel route dns $TUNNEL_NAME $HOSTNAME
    echo ""
    echo "DNS configured: $HOSTNAME -> $TUNNEL_NAME"
fi

# Create systemd service (Linux only)
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo ""
    read -p "Install as systemd service? (y/N): " install_service

    if [[ "$install_service" =~ ^[Yy]$ ]]; then
        sudo cloudflared service install
        sudo systemctl enable cloudflared
        sudo systemctl start cloudflared
        echo "Service installed and started."
    fi
fi

# Create launchd service (macOS)
if [[ "$OSTYPE" == "darwin"* ]]; then
    echo ""
    read -p "Install as launchd service (auto-start on boot)? (y/N): " install_service

    if [[ "$install_service" =~ ^[Yy]$ ]]; then
        PLIST_FILE="$HOME/Library/LaunchAgents/com.cloudflare.cloudflared.plist"

        cat > "$PLIST_FILE" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.cloudflare.cloudflared</string>
    <key>ProgramArguments</key>
    <array>
        <string>$(which cloudflared)</string>
        <string>tunnel</string>
        <string>run</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/cloudflared.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/cloudflared.error.log</string>
</dict>
</plist>
EOF

        launchctl load "$PLIST_FILE"
        echo "Service installed and started."
        echo "Logs: /tmp/cloudflared.log"
    fi
fi

echo ""
echo "=================================="
echo "Setup Complete!"
echo "=================================="
echo ""
echo "To start the tunnel manually:"
echo "  cloudflared tunnel run $TUNNEL_NAME"
echo ""

if [[ -n "$HOSTNAME" ]]; then
    echo "Your J.A.R.V.I.S hub will be available at:"
    echo "  https://$HOSTNAME"
else
    echo "Your tunnel URL:"
    echo "  Run 'cloudflared tunnel run $TUNNEL_NAME' to see the URL"
fi

echo ""
echo "Update your iOS client with this URL for remote access."
echo ""
